version: 2

models:
  - name: mart_evolucao_ano
    description: "Este mart compara a evolução dos gestores por escola entre os anos de 2019 e 2020."
    columns:
      - name: co_escola
        description: "Código da escola."
      - name: gestor_2019
        description: "ID do gestor da escola em 2019."
        tests:
          - not_null
      - name: gestor_2020
        description: "ID do gestor da escola em 2020."
        tests:
          - not_null
      - name: houve_troca
        description: "Indica se houve troca de gestor na escola entre 2019 e 2020 (1 = sim, 0 = não)."
